"""
Django settings for clinic project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url


BASE_DIR = Path(__file__).resolve().parent.parent






SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-test-key')




DEBUG = True

ALLOWED_HOSTS = ['*']




INSTALLED_APPS = [
    "unfold",  
    "unfold.contrib.filters",  
    "unfold.contrib.forms",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'patients',
    'users',
    'django_cleanup.apps.CleanupConfig',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clinic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'patients.context_processors.sms_credit_balance'
            ],
        },
    },
]

WSGI_APPLICATION = 'clinic.wsgi.application'





DATABASES = {
    'default': dj_database_url.config(default='sqlite:///db.sqlite3')
}





AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]





LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True





STATIC_URL = 'static/'




DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


LOGIN_URL = 'login'           
LOGIN_REDIRECT_URL = 'patient_list'  
LOGOUT_REDIRECT_URL = 'login' 

UNFOLD = {
    
    "SITE_TITLE": "سامانه QEEG",
    "SITE_HEADER": "پنل مدیریت کلینیک",
    "SITE_URL": "/", 
    
    
    
    

    
    
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246", 
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
        },
    },

    
    "SIDEBAR": {
        "show_search": True,  
        "show_all_applications": True, 
        
        
        "navigation": [
            {
                "title": "دسترسی سریع",
                "separator": True, 
                "items": [
                    {
                        "title": "مشاهده سایت",
                        "icon": "desktop_windows", 
                        "link": "patient_list", 
                    },
                ],
            },
        ],
    },
}


SMS_API_KEY = '1Y7Cew52CazJ4SsuIiE3LZaYxofiRZTMconkkUkATpgUbMtM'
SMS_LINE_NUMBER = 9982008947  # عدد (Integer)
SMS_BASE_URL = "https://api.sms.ir/v1/"