# Generated by Django 5.2.6 on 2025-12-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='test', max_length=11, verbose_name='شماره تماس'),
            preserve_default=False,
        ),
    ]
